events {
  worker_connections 1024;
}

http {
  server_tokens off;

  server {
    listen 80;
    server_name blogsbymadesh.live www.blogsbymadesh.live admin.blogsbymadesh.live api.blogsbymadesh.live;

    location /.well-known/acme-challenge/ {
      root /var/www/certbot;
    }

    location / {
      return 200 'OK';
      add_header Content-Type text/plain;
    }
  }
}
